### ISSUE TITLE
Fix GitHub Actions Tests

### ISSUE THREAD

**Issue by johneastman** [johneastman/Shopper#53]
#### Errors with api_level
* 30 and 31 cause a connection refused error
* 29 causes the tests to run, but some fail with this error:
  ```
  com.john.shopper.ShoppingListItemsTest > testSetAllItemsAsIncomplete[test(AVD) - 10] FAILED 
	androidx.test.espresso.PerformException: Error performing 'single click - At Coordinates: 251, 396 and precision: 16, 16' on view 'an instance of android.widget.TextView and view.getText() with or without transformation to match: is "ADD"'.
	at androidx.test.espresso.PerformException$Builder.build(PerformException.java:1)

  com.john.shopper.ShoppingListItemsTest > testClearAllItems[test(AVD) - 10] FAILED 
	androidx.test.espresso.PerformException: Error performing 'single click - At Coordinates: 251, 396 and precision: 16, 16' on view  'an instance of android.widget.TextView and view.getText() with or without transformation to match: is "ADD"'.
	at androidx.test.espresso.PerformException$Builder.build(PerformException.java:1)

  com.john.shopper.ShoppingListItemsTest > testUpdateItemsOnMove[test(AVD) - 10] FAILED 
	androidx.test.espresso.PerformException: Error performing 'single click - At Coordinates: 251, 396 and precision: 16, 16' on view 'an instance of android.widget.TextView and view.getText() with or without transformation to match: is "ADD"'.
	at androidx.test.espresso.PerformException$Builder.build(PerformException.java:1)

  com.john.shopper.ShoppingListItemsTest > testSetAllItemsAsComplete[test(AVD) - 10] FAILED 
	androidx.test.espresso.PerformException: Error performing 'single click - At Coordinates: 251, 396 and precision: 16, 16' on view 'an instance of android.widget.TextView and view.getText() with or without transformation to match: is "ADD"'.
	at androidx.test.espresso.PerformException$Builder.build(PerformException.java:1)
  ```

**Comment by johneastman** [comment]
The tests were not passing because the keyboard was covering the buttons, which meant espresso couldn't find them. To fix this, I added `.perform(closeSoftKeyboard())` before clicking each button.

Commits:
* https://github.com/johneastman/Shopper/commit/eda9b4fcb390d75a9f7ab685369adf1f15f79589
* https://github.com/johneastman/Shopper/commit/4404466688eeabad54945289909e6df199247517
